environment:
  name: IceCreamFactory
  project: cdf-bootcamp-78-test
  type: dev
  selected:
  - modules/bootcamp/data_foundation
  - modules/bootcamp/ice_cream_api
  - modules/bootcamp/use_cases/oee

variables:
  modules:
    bootcamp:
      CDF_PROJECT: ${CDF_PROJECT}
      IDP_CLIENT_ID: ${IDP_CLIENT_ID}
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET}
      IDP_TENANT_ID: ${IDP_TENANT_ID}
      # This is related to the cluster where the CDF project is hosted.
      CDF_URL: https://westeurope-1.cognitedata.com
      IDP_SCOPES: https://westeurope-1.cognitedata.com/.default
      IDP_TOKEN_URL: ${IDP_TOKEN_URL}
      # Groups
      # OBJECT ID FOR TEST/PROD DATA DEVELOPER ENTRA GROUP
      data_developer_source_id: ${DATA_DEVELOPER_OBJECT_ID}
      # OBJECT ID FOR TEST/PROD DATA PIPELINE OEE ENTRA GROUP
      data_pipeline_oee_source_id: ${DATA_PIPELINE_OEE_OBJECT_ID}
      # OBJECT ID FOR TEST/PROD ADMIN TK ENTRA GROUP
      readwrite_source_id: a9bb9da4-5416-4390-8fd7-ccbf24af4b3d
      # OBJECT ID FOR TEST/PROD ADMIN TK ENTRA GROUP
      readonly_source_id: a9bb9da4-5416-4390-8fd7-ccbf24af4b3d
      # OBJECT ID FOR TEST/PROD ADMIN TK ENTRA GROUP
      icapi_extractors_source_id: ${ICAPI_EXTRACTORS_OBJECT_ID}
      # Client Ids
      data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID}
      data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET}
      icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
      icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}
      
      # Custom
      icapi_ds_external_id: ds_icapi
      uc_oee_ds_external_id: ds_uc_oee
